__title__ = 'jsv'
__description__ = 'A compact representation of bulk JSON objects.'
__url__ = 'http://jsv-io.org'
__version__ = None
__commit_hash__ = None
__author__ = 'Alex Kovner'
__author_email__ = 'dev@alexkovner.com'
__license__ = 'MIT'
__copyright__ = 'Copyright 2018 Alex Kovner'
